name: webstack Actions # åå­—è‡ªå–

on:
  push:
    branches:
      - main # è¿™é‡Œçš„æ„æ€æ˜¯å½“ main åˆ†æ”¯å‘ç”Ÿ push çš„æ—¶å€™ï¼Œè¿è¡Œä¸‹é¢çš„ jobs

jobs:
  deploy:
    runs-on: ubuntu-20.04 # åœ¨ä»€ä¹ˆç¯å¢ƒè¿è¡Œä»»åŠ¡
    steps:
      - uses: actions/checkout@v3 # å¼•ç”¨ actions/checkout è¿™ä¸ª actionï¼Œä¸æ‰€åœ¨çš„ github ä»“åº“åŒå
        with:
          submodules: true # Fetch Hugo themes (true OR recursive) è·å– submodule ä¸»é¢˜
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Build Site
        run: |
          pwd
          node -v
          yarn
          yarn build

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3 # ä¸€ä¸ªè‡ªåŠ¨å‘å¸ƒ github pages çš„ action
        with:
          external_repository: aa1049372051/npm-vue-web # å‘å¸ƒåˆ°å“ªä¸ª repo
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # å‘å¸ƒåˆ°å…¶ä»– repo éœ€è¦åœ¨å¯¹åº”çš„ repo ä¸Šç²˜è´´ç”Ÿæˆçš„ personal_access_token
          #1. åˆ›å»º Personal_Access_Tokenï¼š
          #   GitHub ä¸ªäººè´¦å· -> Settings -> Developer settings -> Personal access tokens ->  Tokens (classic) -> New personal access token (classic)
          #   - Expiration: No expiration
          #   - Select scopes: å…¨é€‰
          #2. ç²˜è´´ Personal_Access_Tokenï¼š
          #   è¿›å…¥ç›®æ ‡ repo -> Settings -> Security -> Secrets and variables -> Actionsï¼Œé€‰æ‹© New repository secret -> ç²˜è´´å‰é¢ç”Ÿæˆçš„ personal_access_token
          publish_dir: ./storybook-static
          #æ³¨æ„è¿™é‡ŒæŒ‡çš„æ˜¯ Pages è¦å‘å¸ƒå“ªä¸ªæ–‡ä»¶å¤¹çš„å†…å®¹ï¼Œè€Œä¸æ˜¯æŒ‡å‘å¸ƒåˆ°ç›®æ ‡ä»“åº“çš„ä»€ä¹ˆä½ç½®ï¼›å› ä¸º hugo é»˜è®¤ç”Ÿæˆé™æ€ç½‘é¡µåˆ° public æ–‡ä»¶å¤¹ï¼Œæ‰€ä»¥è¿™é‡Œå‘å¸ƒ public æ–‡ä»¶å¤¹é‡Œçš„å†…å®¹ã€‚
          publish_branch: gh-pages # å‘å¸ƒåˆ°å“ªä¸ª branch
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}

      #ğŸ‘‡ Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #ğŸ‘‡ Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
